// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 1() {
    driver.get("https://www.gittigidiyor.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("k")).click();
    driver.findElement(By.name("k")).sendKeys("bilgisayar");
    driver.findElement(By.cssSelector(".ymqsgy-2:nth-child(1) .ymqsgy-3")).click();
    driver.findElement(By.cssSelector(".gg-uw-6:nth-child(1) .img-cont")).click();
    js.executeScript("window.scrollTo(0,300)");
    {
      WebElement element = driver.findElement(By.id("add-to-basket"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("add-to-basket")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,255)");
    driver.findElement(By.linkText("Sepete Git")).click();
    driver.findElement(By.cssSelector(".gg-input-select > .amount")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".gg-input-select > .amount"));
      dropdown.findElement(By.xpath("//option[. = '2']")).click();
    }
    driver.findElement(By.cssSelector(".gg-input-select > .amount")).click();
    driver.findElement(By.cssSelector(".row > .btn-delete > .gg-icon")).click();
  }
}
